---
apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    component: smoke-test
    group: poc
    app: smoke-test
    provider: fabric8
    version: 1.0-SNAPSHOT
  name: smoke-test
spec:
  output:
    to:
      kind: ImageStreamTag
      name: smoke-test:latest
  resources:
    limits:
      memory: 1G
    requests:
      memory: 0.7G
  strategy:
    sourceStrategy:
      env:
      - name: BUILD_LOGLEVEL
        value: "5"
      - name: ARTIFACT_DIR
        value: ""
      - name: MAVEN_ARGS
        value: package -DskipTests -Dfabric8.skip -e -B
      - name: MAVEN_ARGS_APPEND
        value: ""
      - name: MAVEN_MIRROR_URL
        value: ""
      forcePull: true
      from:
        kind: ImageStreamTag
        name: fuse7-java-openshift:1.3
        namespace: openshift
      incremental: true
    type: Source
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
